document.addEventListener('DOMContentLoaded', async () => {
  if(window.KagakuCloud?.questionsReady) await window.KagakuCloud.questionsReady;
  const list=document.getElementById('test-list'),area=document.getElementById('test-area');
  const c=window.KagakuCloud?.getClient?.();
  if(!c){list.innerHTML='<div class="test-card">Supabase接続が設定されていません。</div>';return;}
  const {data:tests,error}=await c.rpc('get_published_tests');
  if(error){list.innerHTML='<div class="test-card">テスト機能の設定がまだ完了していません。管理者がFINAL_SETUP.sqlを実行してください。</div>';return;}
  if(!tests?.length){list.innerHTML='<div class="test-card">現在公開されているテストはありません。</div>';return;}
  list.innerHTML=tests.map(t=>`<article class="test-item"><div><h2>${esc(t.title)}</h2><p>${esc(t.description||'')}</p><div class="test-meta">${toIds(t.question_ids).length}問 ・ ${Number(t.time_limit_seconds)?`${Math.ceil(Number(t.time_limit_seconds)/60)}分制限`:'時間制限なし'}</div></div><button class="btn btn-primary" data-test="${t.id}">挑戦する</button></article>`).join('');
  document.querySelectorAll('[data-test]').forEach(b=>b.addEventListener('click',()=>startTest(tests.find(t=>t.id===b.dataset.test))));
  function toIds(v){return Array.isArray(v)?v:(typeof v==='string'?JSON.parse(v||'[]'):[])}
  function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  function startTest(t){const ids=toIds(t.question_ids);const qs=ids.map(id=>KagakuData.questions.find(q=>q.id===id)).filter(Boolean);if(!qs.length){alert('このテストに登録された問題が見つかりません。');return}let i=0,answers={};const started=Date.now();const limit=Number(t.time_limit_seconds)||0;list.hidden=true;area.hidden=false;render();let timer=setInterval(()=>{if(!limit)return;const remain=Math.max(0,limit-Math.floor((Date.now()-started)/1000));const el=document.getElementById('test-timer');if(el){el.textContent=`残り ${Math.floor(remain/60)}:${String(remain%60).padStart(2,'0')}`;el.classList.toggle('warn',remain<=30)}if(remain<=0){clearInterval(timer);finish(true)}},250);
    function render(){const q=qs[i],selected=answers[q.id];area.innerHTML=`<div class="test-card"><div style="display:flex;justify-content:space-between;gap:12px"><span class="eyebrow">第${i+1}問 / ${qs.length}</span><span id="test-timer" class="timer">${limit?'計測中':'時間制限なし'}</span></div><div class="test-question" style="margin:16px 0">${esc(q.question)}</div><div class="options-grid">${q.options.map((o,n)=>`<button class="option-btn ${selected===n?'selected':''}" data-opt="${n}">${n+1}. ${esc(o)}</button>`).join('')}</div><div style="display:flex;justify-content:flex-end;margin-top:18px"><button id="test-next" class="btn btn-primary">${i===qs.length-1?'採点する':'次の問題'}</button></div></div>`;document.querySelectorAll('[data-opt]').forEach(b=>b.onclick=()=>{answers[q.id]=Number(b.dataset.opt);render()});document.getElementById('test-next').onclick=()=>{if(answers[q.id]===undefined){alert('選択肢を1つ選んでください。');return}if(i===qs.length-1)finish(false);else{i++;render()}}}
    async function finish(timeout){clearInterval(timer);const elapsed=Math.round((Date.now()-started)/1000);let score=0;qs.forEach(q=>{if(answers[q.id]===q.answerIndex)score++});const session=await c.auth.getSession();const uid=session.data.session?.user?.id;if(uid)c.from('test_results').insert({test_id:t.id,user_id:uid,score,total:qs.length,time_seconds:elapsed,answers}).then(()=>{});area.innerHTML=`<div class="test-card"><div class="eyebrow">${timeout?'時間終了':'テスト完了'}</div><h2 style="text-align:center">${esc(t.title)}</h2><div class="result-score">${score} / ${qs.length} 点</div><p style="text-align:center">正答率 ${Math.round(score/qs.length*100)}% ・ 所要 ${Math.floor(elapsed/60)}分${elapsed%60}秒</p><div class="answer-review">${qs.map((q,n)=>`<div><strong>第${n+1}問 ${answers[q.id]===q.answerIndex?'⭕ 正解':'❌ 不正解'}</strong><br>${esc(q.explanation||'解説なし')}</div>`).join('')}</div><div style="text-align:center;margin-top:18px"><button class="btn btn-outline" id="back-tests">テスト一覧へ</button></div></div>`;document.getElementById('back-tests').onclick=()=>location.reload()}
  }
});
